### ISSUE TITLE
string[] as argument to WithPrimaryKey()

### ISSUE THREAD

**Issue by olovericson** [drunkcod/DataBoss#1]
It would be nice if the 
IDataPackageResourceBuilder WithPrimaryKey(string field, params string[] parts);
could take a  WithPrimaryKey(params string[] fields); directly to avoid having to do:
WithPrimaryKey(primaryKeys.First(), primaryKeys.Skip(1).ToArray());

**Comment by drunkcod** [comment]
I'll aligin the PrimareyKey definitions to the ForeignKey form making them both take arrays. 
This will be in the next version.
