### ISSUE TITLE
Write decimalChar in schema for default value?

### ISSUE THREAD

**Issue by mobsports** [drunkcod/DataBoss#11]
When we save a data package with a `CultureInfo.InvariantCulture` using SaveZip we don't get the `decimalChar` set for the number field in the schema. Seems that it is ignoring to do that when `decimalChar` is the default ("."). Is it possible to always get the `decimalChar` in the schema even if it is a `.` ?

For example:
`dp.SaveZip("C:\\temp\\testingdatapackagewithculture.zip", CultureInfo.GetCultureInfo("sv-SE"));`

Results in:
      `
"schema": {
        "fields": [
          {
            "name": "Value",
            "type": "number",
            "decimalChar": ",",
            "constraints": {
              "required": true
           ...
`

Best Regards,
Devsports,
Mats, Susanne, Dhanush.

**Comment by drunkcod** [comment]
There's currently no option for that, but I can see value in having it.

Expect an update sometime next week.

**Comment by drunkcod** [comment]
109 just dropped that enables you to request a explicit writer mode by passing an appropriatley configured `DataPackageSaveOptions` 

Looks like this: `db.Save("<path>", new DataPackageSaveOptions { DefaultValueHandling = DataPackageDefaultValueHandling.Explicit });`

You'll also find the `Culture` option on the same object so you can simply use the overloads taking the `DataPackageSaveOptions` rather than the `CultureInfo` version.

**Comment by mobsports** [comment]
Thank you so much!!!

Best Regards,
Devsports,
Mats, Susanne, Dhanush.

**Comment by mobsports** [comment]
Hi,
When we save a DataPackage with `DataPackageDefaultValueHandling.Explicit`, it adds ` "decimalChar": "."` to all the fields in the schema not only for `numbers` but also for `strings` and other types.

**For Example:**
`var dp = new DataPackage();`
`dp.AddResource("numbers", () => SequenceDataReader.Items(new { Value = 1.7, Bla = "text", BlaInt = 2 }));`
`dp.SaveZip("C:\\temp\\testInvariant6.zip", new DataPackageSaveOptions{ Culture = new CultureInfo("sv-SE"), DefaultValueHandling = DataPackageDefaultValueHandling.Explicit});`

**Schema:**
`{
  "resources": [
    {
      "name": "numbers",
      "path": "numbers.csv",
      "format": "csv",
      "dialect": {
        "delimiter": ";",
        "header": true
      },
      "schema": {
        "fields": [
          {
            "name": "Value",
            "type": "number",
            "decimalChar": ",",
            "constraints": {
              "required": true
            }
          },
          {
            "name": "Bla",
            "type": "string",
            "decimalChar": "."
          },
          {
            "name": "BlaInt",
            "type": "integer",
            "decimalChar": ".",
            "constraints": {
              "required": true
            }
          }
        ]
      }
    }
  ]
}`

**Comment by drunkcod** [comment]
That does indeed seem more than a bit excessive.

Thanks for the notification I'll amend that asap.

**Comment by drunkcod** [comment]
This should now be fixed in .110 being indexed as I write this. Sorry for the hassle.

**Comment by mobsports** [comment]
Great! Thank you!
