### ISSUE TITLE
Being able save zip to a stream

### ISSUE THREAD

**Issue by olovericson** [drunkcod/DataBoss#2]
It would be awesome if it was possible to save a package as zip to a stream to avoid having to do this dance:
public void SaveTo(Stream stream) {            
            var fileName = Path.GetTempFileName();
            dataPackage.SaveZip(fileName, CultureInfo.InvariantCulture);

            using (var fileStream = File.OpenRead(fileName)) {
                fileStream.CopyTo(stream);
            }
            
            File.Delete(fileName);
}

**Comment by drunkcod** [comment]
Fixed and will ship as part of .73.
