### ISSUE TITLE
Into with an active SqlTransaction goes boom on my machine

### ISSUE THREAD

**Issue by Rklasens** [drunkcod/DataBoss#5]
[Into temp table with transactions.zip](https://github.com/drunkcod/DataBoss/files/8419542/Into.temp.table.with.transactions.zip)

Run it against a local db of your choosing, explodes because of underlying transaction

**Comment by drunkcod** [comment]
Into overload with a transaction will be in the next release, they already existed for Insert so it was a clear oversight on my part.
